### ISSUE TITLE
upgrade version of elasticsearch

### ISSUE THREAD

**Issue by silky** [scirate/scirate#354]
see #351 and #353 

the elastic log were half of this

**Comment by silky** [comment]
there's a few timeouts like this:

```
A Faraday::Error::ConnectionFailed occurred in feeds#show:

end of file reached (EOFError)
lib/search.rb:215:in `es_find'
```

**Comment by silky** [comment]
these requests are actually all from the bing crawling robot.

**Comment by silky** [comment]
jeez, this is going to be big item

https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html

because we're so behind the times in terms of versions

**Comment by silky** [comment]
i guess we don't need to formally upgrade; we can just be down briefly while we re-index

**Comment by silky** [comment]
of course, this requires dropping "stretcher" and using this - https://github.com/elastic/elasticsearch-ruby

which requires upgrading ruby to 2.4

**Comment by silky** [comment]
here i am just hoping that changing the Gemfile to point to ruby 2.4.1 works

good luck.

**Comment by silky** [comment]
that couldn't install puma

now i'm trying to use a modern version of ruby, but rbenv only shows ruby up to 2.4.2 ????

**Comment by silky** [comment]
puma still fails with 2.7.2

**Comment by silky** [comment]
fixed puma - https://stackoverflow.com/a/44011211

**Comment by silky** [comment]
byebug doesn't install because of a bug.

**Comment by silky** [comment]
i officially give up

i'm now here at this error:

```
12:14 PM noon φ scirate (master*) bundle exec -- rails server
Traceback (most recent call last):
        22: from bin/rails:4:in `<main>'
        21: from bin/rails:4:in `require'
        20: from /home/noon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
        19: from /home/noon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        18: from /home/noon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:73:in `server'
        17: from /home/noon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
        16: from /home/noon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require'
        15: from /home/noon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-4.2.10/lib/rails/commands/server.rb:4:in `<top (required)>'
        14: from /home/noon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-4.2.10/lib/rails/commands/server.rb:4:in `require'
        13: from /home/noon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-4.2.10/lib/rails.rb:11:in `<top (required)>'
        12: from /home/noon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-4.2.10/lib/rails.rb:11:in `require'
        11: from /home/noon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-4.2.10/lib/rails/application.rb:7:in `<top (required)>'
        10: from /home/noon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-4.2.10/lib/rails/application.rb:7:in `require'
         9: from /home/noon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-4.2.10/lib/rails/engine.rb:1:in `<top (required)>'
         8: from /home/noon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-4.2.10/lib/rails/engine.rb:1:in `require'
         7: from /home/noon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-4.2.10/lib/rails/railtie.rb:2:in `<top (required)>'
         6: from /home/noon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-4.2.10/lib/rails/railtie.rb:2:in `require'
         5: from /home/noon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-4.2.10/lib/rails/configuration.rb:2:in `<top (required)>'
         4: from /home/noon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-4.2.10/lib/rails/configuration.rb:2:in `require'
         3: from /home/noon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-4.2.10/lib/active_support/core_ext/object.rb:3:in `<top (required)>'
         2: from /home/noon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-4.2.10/lib/active_support/core_ext/object.rb:3:in `require'
         1: from /home/noon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-4.2.10/lib/active_support/core_ext/object/duplicable.rb:106:in `<top (required)>'
/home/noon/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-4.2.10/lib/active_support/core_ext/object/duplicable.rb:111:in `<class:BigDecimal>': undefined method `new' for BigDecimal:Class (NoMethodError)
```

this has got literally nothing to do with any scirate code

dearest ruby. what the hell is going on? why are you bringing your big-decimal problems to me?

**Comment by silky** [comment]
after some advice, i switched to 2.6.6, and now get a _different_ unrelated error:

```
12:57 PM noon φ scirate (master*) bundle exec -- rails server                                                                                                  Mon Oct 05
/home/noon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-4.2.10/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
Traceback (most recent call last):
        28: from bin/rails:4:in `<main>'
        27: from bin/rails:4:in `require'
        26: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
        25: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        24: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:75:in `server'
        23: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:75:in `tap'
        22: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:78:in `block in server'
        21: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:78:in `require'
        20: from /home/noon/dev/scirate/config/application.rb:9:in `<top (required)>'
        19: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-4.2.10/lib/active_support/deprecation/instance_delegator.rb:19:in `silence'
        18: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-4.2.10/lib/active_support/deprecation/reporting.rb:34:in `silence'
        17: from /home/noon/dev/scirate/config/application.rb:10:in `block in <top (required)>'
        16: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler.rb:114:in `require'
        15: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/runtime.rb:65:in `require'
        14: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/runtime.rb:65:in `each'
        13: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/runtime.rb:76:in `block in require'
        12: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/runtime.rb:76:in `each'
        11: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require'
        10: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/runtime.rb:81:in `require'
         9: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/delayed_job_active_record-4.0.3/lib/delayed_job_active_record.rb:5:in `<top (required)>'
         8: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:64:in `backend='
         7: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
         6: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
         5: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
         4: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
         3: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/delayed_job-4.0.6/lib/delayed/serialization/active_record.rb:2:in `<top (required)>'
         2: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/delayed_job-4.0.6/lib/delayed/serialization/active_record.rb:3:in `<module:ActiveRecord>'
         1: from /home/noon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/delayed_job-4.0.6/lib/delayed/serialization/active_record.rb:4:in `<class:Base>'
/home/noon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-4.2.10/lib/active_record/dynamic_matchers.rb:26:in `method_missing': undefined method `yaml_as' for ActiveRecord::Base:Class (NoMethodError)
Did you mean?  yaml_tag
```

**Comment by silky** [comment]
i'm now down to 2.4.0, which seems to work

**Comment by JacksonBates** [comment]
Just another productive day in the dimly lit ruby mines

**Comment by silky** [comment]
yeah

i've ended up losing the plot

i can now connect to my new elasticsearch version; but the new api ( instead of Stretcher using elasticsearch ) is a bit different, and i'm struggling to get it all working

maybe i'll push it as a broken branch for later ; i need to take a break for a bit.

**Comment by silky** [comment]
https://github.com/scirate/scirate/tree/elastic-doom

**Comment by silky** [comment]
just to re-cap the plan here:

1. we need to upgrade elasticsearch to something modern. we're on a 5-year-old version.
2. i've "started" this on the branch "elastic-doom" ( https://github.com/scirate/scirate/compare/elastic-doom?expand=1 )
3. the main thing to do is switch out the "stretcher" library with the "elasticsearch-api".

i'd guess this is around a weekends-worth of work for someone familiar with ruby.

if we get this done, we get heaps of wins, notably:

1. we can get the travis build working again
2. probably new elastic search is better
3. we're back on a modern version of ruby
4. probably other life benefits

**Comment by silky** [comment]
this is now _almost_ there 

( and @mispy is the best programmer! )
