### ISSUE TITLE
notify error error while syncing

### ISSUE THREAD

**Issue by silky** [scirate/scirate#413]
While running `./sync.sh`

```
rake aborted!
NoMethodError: undefined method `notify_error' for SciRate:Module
/home/scirate/scirate/lib/arxiv_import.rb:155:in `_import_papers'
/home/scirate/scirate/lib/arxiv_import.rb:19:in `block in papers'
/home/scirate/scirate/lib/arxiv_import.rb:18:in `papers'
/home/scirate/scirate/lib/tasks/arxiv_oai_update.rake:28:in `block (2 levels) in <top (required)>'
/home/scirate/scirate/lib/tasks/arxiv_paper_sync.rake:14:in `block (2 levels) in <top (required)>'
/home/scirate/.rbenv/versions/2.6.6/bin/bundle:23:in `load'
/home/scirate/.rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
Tasks: TOP => arxiv:oai_update
```

**Comment by silky** [comment]
i think my "fix" broke other things - https://github.com/scirate/scirate/commit/fc86873cc98823987c7fc3dd50022fa14cf53fd4

:shrug:
